[package]
name = "libplugin"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
once_cell = "1.3.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
host = { path = "../host" }
