[package]
name = "game_kernel"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
wasmer-runtime = "0.14"
libplugin = { path = "../libplugin" }
