[package]
name = "plugin_b"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
libplugin = { path = "../libplugin" }
render = { path = "../render" }
