[package]
name = "loopback"
version = "0.1.0"
authors = ["Duncan Freeman <dfreeman@lucidyne.com>"]
edition = "2018"

[dependencies]
futures = "0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "loopback_benchmark"
harness = false
